[package]
name = "futures-fs-test"
version = "0.1.0"
authors = ["Toshiya Nakakura <nakakura@me.com>"]

[dependencies]
futures = "*"
futures-fs = "*"
bytes = "*"
tokio = "*"
nom = "3.2.1"
either = "*"
